import { Link } from "react-router";

export function Terms() {
  return (
    <div className="min-h-screen px-6 py-12" style={{ background: "var(--navy-bg)" }}>
      <div className="max-w-[640px] mx-auto">
        <Link
          to="/"
          className="text-sm no-underline transition-colors hover:text-white/80"
          style={{ color: "var(--layer1-blue)" }}
        >
          &larr; Back to home
        </Link>

        <h1
          className="text-[28px] font-normal text-white mt-8 mb-2"
          style={{ fontFamily: "var(--font-headline)" }}
        >
          Terms of Service
        </h1>
        <p className="text-[13px] text-white/30 mb-10">Effective: April 6, 2026</p>

        <div className="space-y-8 text-[15px] leading-relaxed text-white/50" style={{ fontFamily: "var(--font-body)" }}>
          <div>
            <h2 className="text-[18px] font-semibold text-white mb-3">About this service</h2>
            <p>
              Finnopolis is an AI-curated financial news aggregator. We summarise and link to publicly available news
              articles. We are not a financial advisor and nothing on this site constitutes investment advice.
            </p>
          </div>

          <div>
            <h2 className="text-[18px] font-semibold text-white mb-3">Not financial advice</h2>
            <p>
              All content on Finnopolis — including AI-generated summaries, consensus signals, analyst data, and
              inference sections — is provided for informational purposes only. You should always do your own research
              and consult a qualified financial professional before making investment decisions.
            </p>
          </div>

          <div>
            <h2 className="text-[18px] font-semibold text-white mb-3">AI-generated content</h2>
            <p>
              Article summaries, briefs, and inference sections are generated by AI models. While we strive for accuracy,
              AI-generated content may contain errors. Content labelled "AI INFERENCE" is explicitly not sourced from
              analyst data and should be treated as speculative.
            </p>
          </div>

          <div>
            <h2 className="text-[18px] font-semibold text-white mb-3">Third-party content</h2>
            <p>
              We link to articles from third-party publications. We do not control or endorse the content of those
              publications. Original article copyrights belong to their respective publishers.
            </p>
          </div>

          <div>
            <h2 className="text-[18px] font-semibold text-white mb-3">Service availability</h2>
            <p>
              Finnopolis is provided "as is" without warranties. We may modify, suspend, or discontinue the service at
              any time.
            </p>
          </div>

          <div>
            <h2 className="text-[18px] font-semibold text-white mb-3">Contact</h2>
            <p>
              Questions? Email{" "}
              <a href="mailto:carlo@finnopolis.com" className="no-underline hover:underline" style={{ color: "var(--layer1-blue)" }}>
                carlo@finnopolis.com
              </a>.
            </p>
          </div>
        </div>

        <div className="mt-12 pt-6 text-[12px] text-white/20" style={{ borderTop: "1px solid rgba(255,255,255,0.1)" }}>
          <Link to="/" className="no-underline hover:underline mr-3" style={{ color: "var(--layer1-blue)" }}>
            Back to Finnopolis
          </Link>
          &middot;
          <Link to="/privacy" className="no-underline hover:underline ml-3" style={{ color: "var(--layer1-blue)" }}>
            Privacy Policy
          </Link>
          <p className="mt-2">&copy; 2026 Finnopolis</p>
        </div>
      </div>
    </div>
  );
}
