-- Migration: Create seed_bundles() function for v2.3 seeder
-- Date: 2026-04-26
-- Description: Server-side function that accepts a JSON manifest array and
--   inserts into ai_articles + article_topics. Replaces per-bundle DO blocks
--   generated by the seeder skill, cutting token usage by ~60%.

CREATE OR REPLACE FUNCTION seed_bundles(p_bundles jsonb)
RETURNS TABLE(inserted_count int, article_ids uuid[])
LANGUAGE plpgsql AS $$
DECLARE
  bundle jsonb;
  aid uuid;
  tid uuid;
  v_slug text;
  is_prim boolean;
  ids uuid[] := '{}';
  cnt int := 0;
BEGIN
  FOR bundle IN SELECT * FROM jsonb_array_elements(p_bundles)
  LOOP
    INSERT INTO ai_articles (
      source_url, headline, publication, publication_url,
      published_at, ai_preview, brief, brief_bullets, citations,
      extracted_tickers, analyst_data, finnhub_fetched_at,
      inference_watch, inference_risks, inference_questions,
      consensus_signal, processing_status, model,
      primary_entities, story_magnitude, story_type, story_cluster_id
    ) VALUES (
      NULL,
      bundle->>'headline',
      NULL, NULL,
      (bundle->>'published_at')::timestamptz,
      bundle->>'ai_preview',
      NULL,
      ARRAY(SELECT jsonb_array_elements_text(bundle->'brief_bullets')),
      bundle->'citations',
      ARRAY(SELECT jsonb_array_elements_text(bundle->'extracted_tickers')),
      NULLIF(bundle->'analyst_data', 'null'::jsonb),
      CASE WHEN bundle->'analyst_data' IS NOT NULL AND bundle->'analyst_data' != 'null'::jsonb THEN now() ELSE NULL END,
      ARRAY(SELECT jsonb_array_elements_text(bundle->'inference_watch')),
      ARRAY(SELECT jsonb_array_elements_text(bundle->'inference_risks')),
      ARRAY(SELECT jsonb_array_elements_text(bundle->'inference_questions')),
      bundle->>'consensus_signal',
      'complete',
      'hand-seeded-v2.3',
      bundle->'primary_entities',
      (bundle->>'story_magnitude')::int,
      bundle->>'story_type',
      bundle->>'story_cluster_id'
    )
    RETURNING id INTO aid;

    ids := ids || aid;
    cnt := cnt + 1;

    -- Insert article_topics from topic_slugs
    FOR v_slug IN SELECT jsonb_array_elements_text(bundle->'topic_slugs')
    LOOP
      SELECT id INTO tid FROM topics t WHERE t.slug = v_slug;
      IF tid IS NOT NULL THEN
        is_prim := EXISTS (
          SELECT 1 FROM jsonb_array_elements_text(bundle->'topic_primary_slugs') ps
          WHERE ps = v_slug
        );
        INSERT INTO article_topics (id, article_id, topic_id, relevance, is_primary, tag_source)
        VALUES (
          gen_random_uuid(), aid, tid,
          CASE WHEN is_prim THEN 0.90 ELSE 0.72 END,
          is_prim, 'manual'
        );
      END IF;
    END LOOP;
  END LOOP;

  RETURN QUERY SELECT cnt, ids;
END;
$$;
